# 项目的启动端口
server:
  port: 20001
  error:
    include-message: always

spring:
  application:
    # 定义项目名称
    name: coupon-customer-serv
  main:
    allow-bean-definition-overriding: true # 开启Bean覆盖
  datasource:
    # mysql数据源
    username: root
    password: Zym_0423
    url: jdbc:mysql://1.94.123.205:3306/geekbang_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        server-addr: 1.94.123.205:8848
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        naming-load-cache-at-start: false
        namespace: public
        register-enabled: true
feign:
  client:
    config:
      default: # 全局配置（也可以指定具体Feign客户端名称）
        loggerLevel: FULL # 打印完整的请求/响应日志
logging:
  level:
    feign.Logger: debug
    com.geekbang.coupon.customer: debug
